{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7343675"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.3.0.aar",
          "url": "appcompat-resources-1.3.0.aar",
          "size": 65247,
          "sha512": "ffe305547f90a552f496720a9c82d4915e233f1e51aa1b9a919682513b5ca1877c04b8b5f3bf4a3116d4e9f6c7723fd7b39cdfaf4f9ae574ed92e716709ff9f8",
          "sha256": "b2e199c9139b127533ddea6b4a8eb76f3dd69557bb852cab2d208367b6808d06",
          "sha1": "fd7a8a9933b70c5e1da5243e35682058bc355eb1",
          "md5": "93a71bdeca2fbb14e02cb1f08dc543c7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.3.0.aar",
          "url": "appcompat-resources-1.3.0.aar",
          "size": 65247,
          "sha512": "ffe305547f90a552f496720a9c82d4915e233f1e51aa1b9a919682513b5ca1877c04b8b5f3bf4a3116d4e9f6c7723fd7b39cdfaf4f9ae574ed92e716709ff9f8",
          "sha256": "b2e199c9139b127533ddea6b4a8eb76f3dd69557bb852cab2d208367b6808d06",
          "sha1": "fd7a8a9933b70c5e1da5243e35682058bc355eb1",
          "md5": "93a71bdeca2fbb14e02cb1f08dc543c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-resources-1.3.0-sources.jar",
          "url": "appcompat-resources-1.3.0-sources.jar",
          "size": 39771,
          "sha512": "74468531b69f9c0ae550a7e84def80d98d2de325c6ed36043a50ea8c090f94045901823c256c3ec31dcf68d01e5e92e73fe57066def2330eb2e89c214826914d",
          "sha256": "26455b2dbdbd4326c5ad406960005e48dcdb7fc495b0a3a22aa3a703a18ed302",
          "sha1": "fa1169a9b404f7e905756330af6d13e27dcee50e",
          "md5": "b8ebde19acd29c203a88d334c5d629b4"
        }
      ]
    }
  ]
}
